### ISSUE TITLE
support for 'SKIP' - newly introduced in Robot Framework 4.0

### ISSUE THREAD

**Issue by varun-pandurangi** [reportportal/agent-Python-RobotFramework#96]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

**Describe the bug**

**Steps to Reproduce**
1. Upgrade to latest robot framework 4.0
2. Use SKIP or 'SKIP IF' keywords for few of the tests - New feature in Robotframework 4.0
3. Once the test report (output.xml) is generated
4. Try uploading to report portal using 'post_report.py'

**Expected behavior**
Report should get uploaded to report portal ('SKIP' status should reflect appropriately)

**Actual behavior**
I am seeing an error which says -  'KEY ERROR : NOT RUN'

**Package versions**
Version used : Downloaded from latest Master (as on date)

**Additional context**
Copy of my Console Log:

Traceback (most recent call last):
  File "post_report.py", line 87, in <module>
    main()
  File "post_report.py", line 79, in main
    process(*values)
  File "post_report.py", line 53, in process
    test_run.visit(visitor)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/result/executionresult.py", line 120, in visit
    visitor.visit_result(self)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/result/visitor.py", line 44, in visit_result
    result.suite.visit(self)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/testsuite.py", line 195, in visit
    visitor.visit_suite(self)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/visitor.py", line 87, in visit_suite
    suite.suites.visit(self)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/testsuite.py", line 195, in visit
    visitor.visit_suite(self)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/visitor.py", line 88, in visit_suite
    suite.tests.visit(self)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/testcase.py", line 103, in visit
    visitor.visit_test(self)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/visitor.py", line 111, in visit_test
    test.body.visit(self)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/keyword.py", line 75, in visit
    visitor.visit_keyword(self)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/visitor.py", line 135, in visit_keyword
    kw.body.visit(self)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/keyword.py", line 75, in visit
    visitor.visit_keyword(self)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/visitor.py", line 135, in visit_keyword
    kw.body.visit(self)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/keyword.py", line 75, in visit
    visitor.visit_keyword(self)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robot/model/visitor.py", line 137, in visit_keyword
    self.end_keyword(kw)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robotframework_reportportal/result_visitor.py", line 112, in end_keyword
    listener.end_keyword(kw.name, attrs)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robotframework_reportportal/listener.py", line 97, in end_keyword
    RobotService.finish_keyword(item_id=item_id, keyword=kwd)
  File "/Users/varunpandurangi/Library/Python/3.7/lib/python/site-packages/robotframework_reportportal/service.py", line 191, in finish_keyword
    "status": RobotService.status_mapping[keyword.status],
KeyError: 'NOT RUN'

**Comment by iivanou** [comment]
@varun-pandurangi Are u sure about the version? See [line 191](https://github.com/reportportal/agent-Python-RobotFramework/blob/master/robotframework_reportportal/service.py#L191). Please, update your local copy to the latest version from master.
